### ISSUE TITLE
Add "ProgressReporter" to track module graph building progress

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_graph#103]
It would be great if the graph builder allowed one to slot in a `ProgressReporter` into the graph builder that would be used to report graph building progress to the caller. How I imagine this working like so:

```rs
struct GraphLoadStats {
  /// The number of unique module specifiers that have been seen by the graph,
  /// that are done loading and parsing.
  completed_modules: usize,
  /// The number of unique module specifiers that have been seen by the graph,
  /// including ones where loading is still "in progress".
  seen_modules: usize,
}

trait ProgressReporter {
  /// This function is called after each module is done loading and parsing.
  fn on_load(&self, specifier: &Url, stats: GraphLoadStats);
}
```

This allows for progress indicators to display the progress of building the graph.

**Comment by dsherret** [comment]
I think this could be achieved today by having a custom `Loader` implementation that wraps another `Loader`:

```rs
// very roughly, something along these lines (lazy to do the actual implementation)
struct ProgressLoader<TLoader: Loader> {
  completed_modules: usize,
  seen_modules: usize,
  inner: TLoader,
}

impl<TLoader: Loader> Loader for ProgressLoader<TLoader> {
  fn load(
    &mut self,
    specifier: &ModuleSpecifier,
    is_dynamic: bool,
  ) -> LoadFuture {
    self.seen_modules += 1;
    // call the inner loader here, then after do self.completed_modules + 1
    // or call some callback function or whatever
  }
}
```

**Comment by lucacasonato** [comment]
Yeah, that was my first attempt too, but it doesn't quite work. With this, when I increment `completed_modules`, the `seen_modules` is not yet updated to reflect the added dependencies from the module that was just loaded (because it has not yet been parsed). For the usecase I am trying to solve, I need to know the updated "seen modules" at the time I emit the "load" event.

**Comment by dsherret** [comment]
Ah, I see. So you want an event to occur after a module has been visited, so just before this line:

https://github.com/denoland/deno_graph/blob/a73259d0cf8cdd734305df1bb03a3a1186e2426f/src/graph.rs#L1447

I think probably a progress reporter would be most appropriate like what you suggested. Let's wait to see what @kitsonk says.

**Comment by kitsonk** [comment]
It makes sense to me.
