### ISSUE TITLE
Lazily construct wasm module

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_graph#112]
To support CJS (remove top level await) and scenarios where deno graph is imported but not used, we should support lazily creating a deno_graph.

For example:

```ts
import { load } from "...";

const denoGraph = await load();

await denoGraph.createGraph(....);
```

**Comment by kitsonk** [comment]
I agree with the first point, but:

> deno graph is imported but not used

😕  why would someone do that.  What valid scenarios are there for that?

**Comment by dsherret** [comment]
@kitsonk in ts-morph I'm planning to use it and it would only get called if someone analyzes deno code.

**Comment by kitsonk** [comment]
Thanks that makes sense.  Also, TLA can actually be a challenge with things like Deploy when trying to instantiate the isolate. Having a constructor does make sense.

The pattern here works well (which was adapted from other projects as well):

https://github.com/lucacasonato/comrak-wasm/blob/a8b06e882c43c06de1d1a48e894b6c4f1c0de921/mod.ts#L10-L18

I also do like the `init()` versus `load()`...

**Comment by dsherret** [comment]
The one thing I like about `load` vs `init` is that `load` forces you to call it. I can implement `init` though.

**Comment by dsherret** [comment]
This is done now in #158.
