### ISSUE TITLE
Potentially incorrect `unreachable!`?

### ISSUE THREAD

**Issue by somebody1234** [denoland/deno_graph#15]
WASM throws unreachable when giving arguments to `ModuleGraph.resolveDependency` in the wrong order.

This may be the line causing the error:
https://github.com/denoland/deno_graph/blob/1a9777812fa9e9ead14b7b7701e8fbfafbaf9499/src/lib.rs#L71

**Comment by dsherret** [comment]
This code doesn't exist anymore and has been refactored in such a way that I don't believe this issue will occur.
