### ISSUE TITLE
error: Loading unprepared module

### ISSUE THREAD

**Issue by deckchairlabs** [denoland/deno_graph#167]
tl/dr minimal reproduction lives here https://github.com/deckchairlabs/deno-loading-unprepared-module-error

I'm receiving the following error `error: Loading unprepared module: file:///workspace/deno.json`, when trying to do the below:

**_Note removing the compilerOptions related to jsx, the code runs without issue._**

main.ts
```ts
import config from "./deno.json" assert { type: "json" };
console.log(config);
```

deno.json
```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  },
  "importMap": "./importMap.json"
}
```

importMap.json
```json
{
  "imports": {
    "react": "https://esm.sh/react@18",
    "react/jsx-runtime": "https://esm.sh/react@18/jsx-runtime.js"
  }
}
```

**Comment by kitsonk** [comment]
Even though this was opened first closing in favour of  #166
