### ISSUE TITLE
Location of create_graph and add new element on struct 

### ISSUE THREAD

**Issue by Mehrbod2002** [denoland/deno_graph#218]
I just wonder when I see on forked `deno_graph` , I can't see `create_graph` function  .
confused sorry for this question .

Another question I have , is , shall we add one element in Module struct or Specifier our absolute remote Url which may change on requesting and when we want to vendor it , it doesn't build with main package name and it could be strange name with path  . I have just PR on `deno` which resolved this issue but wonder if we can create vendored path with main package name in importing . appreciate to help out and permit me to do it.

**Comment by dsherret** [comment]
I'm currently in the midst of a big refactor and the `create_graph` function doesn't exist anymore.

After #219 lands, I'm going to upgrade the other crates and then I'm working on integration for the new API here https://github.com/denoland/deno/pull/17692

> Another question I have , is , shall we add one element in Module struct or Specifier our absolute remote Url which may change on requesting and when we want to vendor it , it doesn't build with main package name and it could be strange name with path . I have just PR on `deno` which resolved this issue but wonder if we can create vendored path with main package name in importing . appreciate to help out and permit me to do it.

Could you give an example of what you mean? To help demonstrate the issue, you might want to add a test in https://github.com/denoland/deno/pull/17670 that follows what I outlined here https://github.com/denoland/deno/pull/17670#discussion_r1097859472 -- I believe `deno_graph::ModuleGraph` should already have most information we need like redirected specifiers and such.

**Comment by Mehrbod2002** [comment]
That's great .
Sure I will add tests then 
After your upgrade we can fix the name too then ...
Thanks

**Comment by Mehrbod2002** [comment]
> I'm currently in the midst of a big refactor and the `create_graph` function doesn't exist anymore.
> 
Oh , that's great .

> Could you give an example of what you mean? 
For example if you are going to vendor this link code on file like issue which mention in my PR : 
```javascript
import { load } from "https://x.nest.land/Yenv@1.0.0/mod.ts";

const env = await load({})

```

It makes graph by this crate , first module is this file because of scheme is `file`, then it going to parse it and vendor it . am i right ? 
but when graph wants to load data from this url on importing it will convert to this domain and host : 
```
{ dependencies: {"./src/mod.ts": Dependency { maybe_code: Ok { specifier: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("krnvmnln2bt6577673oo4rze3ntyki3ob24k2qyxhsibzkqz6qaq.arweave.net")), port: None, path: "/VFtWNW3QZ-7__v7c7kck22eFI24OuK1DFzyQHKoZ9AE/src/mod.ts", query: None, fragment: None } ... }
```
this host and domain is on loading data url from this package `https://x.nest.land/Yenv@1.0.0/mod.ts`,
this issue is happing on this crate not `deno` , on my PR it bypass this error , but folder name which vendored package is save is this domain and its path and this will be strange for user .
I can easily add test on PR , but I think if we can solve on exact problem with this crate will be great too .
if we can add absolute domain and url will be great .
or better way is you know what happened with the domain and path on this crate and saved to Module too , to can resolve it on `deno` crate only .

**Comment by Mehrbod2002** [comment]
@dsherret 
The Module doesn't contain information about url and domain of which imported package is , hope you got what I am saying.

**Comment by dsherret** [comment]
The `ModuleGraph` should contain the redirected specifier in the `redirects` property. Then each module and dependency should contain the resolved specifier. The unresolved specifier in the `dependencies` property of a `Module` is the key. I don't think there's anything to solve in deno_graph itself, but if you can demonstrate a test that shows the issue that would be helpful. I believe in this case it's an issue with `deno vendor` not handling redirects to different hosts.
