### ISSUE TITLE
cacheInfo is never used?

### ISSUE THREAD

**Issue by devingfx** [denoland/deno_graph#273]
I couldn't figure out why external modules were always loaded even if already cached using `deno_cache` but it looks like the rust `maybe_cache_info` is ever used anywhere?

https://github.com/denoland/deno_graph/blob/5b79b664bd09e1cb7099b78a559827b7ccd5239f/src/graph.rs#L2145

This means cache strategy is not respected and modules are loaded everytime...

https://github.com/denoland/deno_cache/blob/bc03f82bbda192228d7090b803fb1dd8e7f1d7ff/file_fetcher.ts#L22

**Comment by dsherret** [comment]
It's not set in deno_graph. The implementor may set it in the loader.

https://github.com/denoland/deno_graph/blob/036c9ff0675eae60e7b6a9278daee784fe4b85b6/src/source.rs#L74-L76

That said, cache info is going to remove in the future: https://github.com/denoland/deno/issues/17703

> This means cache strategy is not respected and modules are loaded everytime...

I don't believe the cache info has an affect on any logic other than providing more information in the graph.
