### ISSUE TITLE
`jsr:@deno/graph` fails in instantiating wasm

### ISSUE THREAD

**Issue by hasundue** [denoland/deno_graph#453]
I'm migrating from `x/deno_graph` to `jsr:@deno/graph` but can't get it work even in a primitive example like this:

```typescript
import { createGraph } from "@deno/graph@0.73.1";

const graph = await createGraph(
  "https://deno.land/x/std/testing/asserts.ts",
);
console.log(graph);
```

```
error: (in promise) CompileError: WebAssembly.instantiateStreaming(): expected magic word 00 61 73 6d, found 7b 22 76 65 @+0
    at ext:deno_fetch/26_fetch.js:469:20
    at eventLoopTick (ext:core/01_core.js:168:7)
```

With

```
deno 1.42.3 (release, x86_64-unknown-linux-gnu)
v8 12.3.219.9
typescript 5.4.3
```

It is reproduced in CI environments as well: https://github.com/hasundue/molt/actions/runs/8748662281

ChatGPT told me that the magic word `7b 22 76 65` implies the beginning of a JSON file, so there's probably misinterpretation of responses from JSR or something?

**Comment by lucacasonato** [comment]
Mh, it works for me:

```
> import { createGraph } from "jsr:@deno/graph@0.73.1";

const graph = await createGraph(
  "https://deno.land/x/std/testing/asserts.ts",
);
console.log(graph);

{
  roots: [ "https://deno.land/x/std/testing/asserts.ts" ],
  modules: [
    {
      kind: "esm",
      size: 126,
      mediaType: "TypeScript",
      specifier: "https://deno.land/std@0.223.0/assert/_constants.ts"
    },
    {
      kind: "esm",
      dependencies: [ { specifier: "../fmt/colors.ts", code: [Object] } ],
      size: 12455,
      mediaType: "TypeScript",
      specifier: "https://deno.land/std@0.223.0/assert/_diff.ts"
    },
    {
      kind: "esm",
      size: 783,
      mediaType: "TypeScript",
      specifier: "https://deno.land/std@0.223.0/assert/_format.ts"
    },
    {
      kind: "esm",
      dependencies: [ { specifier: "./assertion_error.ts", code: [Object] } ],
      size: 595,
      mediaType: "TypeScript",
      specifier: "https://deno.land/std@0.223.0/assert/assert.ts"
    },
    {
...
```

Is there anything interesting about your setup? Like a HTTP proxy or corporate VPN or similar?

**Comment by hasundue** [comment]
Nothing, I believe.
But now it's more likely to be a problem with my side so...let me investigate more.
Thank you for a kind response anyway.

**Comment by hasundue** [comment]
Confirmed it working in a clean environment: https://github.com/hasundue/deno_graph_issue_453/actions/runs/8793211200

So it should be related to caches? (since it fails in CI environments with other caches than @deno/graph as I mentioned earlier)
Let me find out the minimal condition to reproduce...

**Comment by hasundue** [comment]
Got it. I removed my `~/.local/share/deno-wasmbuild` then it worked.

Apparently `@deno/graph` was sticking with a 31-byte `.wasm` file:

```
> ll ~/.local/share/deno-wasmbuild/
total 32456
...
-rw-r--r-- 1 hasundue hasundue      31 Apr 19 13:46 978588f494533a0a127c13791e1ab53e5bb33fed46fec0cdba1740d80ee7f261.wasm
...
```

After a successful run, a fat .wasm with the same name was generated in the directory.

Now I can assume that the empty .wasm was created at my first run of `@deno/graph` due to an irregular response from my stub of fetch for testing :sweat: 

As a conclusion, can we patch `jsr:@deno/graph` not to cache an invalid response from the server as a .wasm file?

**Comment by dsherret** [comment]
> But as a conclusion of this story, can we patch jsr:@deno/graph (or wasmbuild) not to cache an invalid response from the server as a .wasm file?

Perhaps it could be updated to fail if the bytes don't start with the wasm magic bytes, but it does fail when not receiving a 200 status code.

I opened https://github.com/denoland/wasmbuild/issues/138
